config/routes.rb
Rails.application.routes.draw do
  root to: 'trips#index'
  get '/about', to: 'pages#about', as: 'about'
  resources :trips, except: [:index] do
    resources :reviews, only: [:new, :create]
    resources :trip_locations, only: [:index, :new, :create] do
        resources :locations, only: [:new, :create]
    end

    collection do
      get :hard
      get :easy
    end
  end
  resources :reviews, only: [:edit, :update, :destroy]
  resources :trip_locations, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :trip_locations, dependent: :destroy
  has_many :trips, through: :trip_locations

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :trip

  validates :rating, presence: true, numericality: { less_than_or_equal_to: 10,  only_integer: true }
  validates :content, presence: true, length: { minimum: 20 }
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :trip_locations, dependent: :destroy
  has_many :locations, through: :trip_locations
  has_one_attached :cover_picture

  validates :title, presence: true

  validates :short_description, presence: true, length: {minimum: 20 }
  validates :difficulty, :length, presence: true, numericality: { only_integer: true }

  def origin_address
    self.trip_locations.find_by(starting_location: true)
  end

  def target_address
    self.trip_locations.find_by(target_location: true)
  end

  def display_origin_address
    if self.trip_locations.any? do |trip_location| trip_location.starting_location == true end
       origin_address.location.address
    else
      "Veuillez ajouter une adresse de départ"
    end
  end

  def display_target_address
    if self.trip_locations.any? do |trip_location| trip_location.target_location == true end
      target_address.location.address
    else
      "Veuillez ajouter une adresse d'arrivée"
    end
  end

  def all_trip_locations
    TripLocation.where(trip_id: self.id)
  end

  def all_locations
    locations = []
    all_trip_locations.each do |trip_location|
      locations << trip_location.location
    end
  locations
  end

  def is_missing_origin_or_target_address
    self.origin_address.nil? || self.target_address.nil?
  end
end

app/models/trip_location.rb
class TripLocation < ApplicationRecord
  belongs_to :trip
  belongs_to :location

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_trip, only: [:new, :create]
    before_action :set_review, only: [:edit, :update, :destroy]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.trip = @trip
        if @review.save
            redirect_to trip_path(@trip)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        @review.update(review_params)
        if @review.save
            redirect_to trip_path(@review.trip)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @review.destroy

        redirect_to trip_path(@review.trip)
    end

    private

    def set_trip
        @trip = Trip.find(params[:trip_id])
    end

    def set_review
        @review = Review.find(params[:id])
    end
    
    def review_params
        params.require(:review).permit(:rating, 
                                       :content
                                      )
    end
end

app/controllers/trip_locations_controller.rb
class TripLocationsController < ApplicationController
  before_action :set_trip, only: [:index, :new, :create]
  before_action :set_trip_location, only: [:edit, :update]

  def new
    if params[:starting_location]
      @trip_location = TripLocation.new(starting_location: params[:starting_location])
    elsif params[:target_location]
      @trip_location = TripLocation.new(target_location: params[:target_location])
    else
      @trip_location = TripLocation.new
    end
    @location = Location.new
  end

  def create
    @trip_location = TripLocation.new(trip_location_params)
    @location = Location.create!(location_params)
    @trip_location.location_id = @location.id
    @trip_location.trip_id = @trip.id
    if @trip_location.save!
        redirect_to trip_path(@trip)
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @location = @trip_location.location
    @location.update(address: params[:location][:address])
    @location.save!
    if @trip_location.save
        redirect_to trip_path(@trip_location.trip)
    else
        render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_trip_location
    @trip_location = TripLocation.find(params[:id])
  end

  def trip_location_params
    params.require(:trip_location).permit(:starting_location,
                                          :target_location
                                          )
  end

  def location_params
    params.require(:location).permit(:address)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:show, :edit, :update, :destroy]

    def index
        @trips = Trip.all
    end

    def show
      @markers = @trip.all_locations.map do |location|
        {
          lat: location.latitude,
          lng: location.longitude
        }
      end
    end

    def new
        @trip = Trip.new
    end

    def create
        @trip = Trip.new(trip_params)
        if @trip.save
          redirect_to trip_path(@trip)
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @trip.update(trip_params)
          redirect_to trip_path(@trip)
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @trip.destroy

        redirect_to root_path, status: :see_other
    end

    def hard
        @trips = Trip.where("difficulty > 5")
    end

    def easy
        @trips = Trip.where("difficulty < 5")
    end

    private

    def trip_params
        params.require(:trip).permit(:title,
                                     :difficulty,
                                     :length,
                                     :short_description,
                                     :cover_picture
                                    )

    end

    def set_trip
        @trip = Trip.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trip_locations_helper.rb
module TripLocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
  def display_origin_address
    if self.trip_locations.any? do |trip_location| trip_location.starting_location == true end
      return origin_address
    else
      "Veuillez ajouter une adresse de départ"
    end
  end

  def display_target_address
    if self.trip_locations.any? do |trip_location| trip_location.target_location == true end
      return target_address
    else
      "Veuillez ajouter une adresse d'arrivée"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lanes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class = "container">
    <div class= "mt-3">
        <h1> Hello world !</h1>
    </div>
</div>

app/views/reviews/_create_form.html.erb
<%= simple_form_for [trip, review] do |f| %>
 <div class= "row g-3">
    <div class = "col-md-6">
      <%= f.input :rating, label: 'Note', hint: "/10", placeholder: "8" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :content, label: "Critique", placeholder: "Une belle balade, un peu sportive sur la fin" %>
    </div>
  </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [trip, review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit %>
<% end %>  

app/views/reviews/_update_form.html.erb
<%= simple_form_for(review) do |f| %>
 <div class= "row g-3">
    <div class = "col-md-6">
      <%= f.input :rating, label: 'Note', hint: "/10", placeholder: "8" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :content, label: "Critique", placeholder: "Une belle balade, un peu sportive sur la fin" %>
    </div>
  </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<div class= "container mt-5">
    <h1>Modifiez cet avis</h1>
    <%= link_to "Retour",trip_path(@review.trip), class: "link-secondary"%>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render "update_form", review: @review %>
    </div>
</div>

app/views/reviews/new.html.erb
<div class= "container mt-5">
    <h1>Laissez votre avis sur cet itinéraire</h1>
    <%= link_to "Retour",trip_path(@trip), class: "link-secondary"%>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render "create_form", review: @review, trip: @trip %>
    </div>
</div>

app/views/trip_locations/_create_form.html.erb
<%= simple_form_for [trip, trip_location] do |f| %>
 <div class= "row g-3">
    <%= simple_fields_for(location) do |l| %>
      <div class = "col-md-12">
        <%= l.input :address %>
      </div>
    <% end %>
    <div class = "col-md-6">
      <%= f.input :starting_location %>
    </div>
    <div class = "col-md-6">
      <%= f.input :target_location %>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/trip_locations/_edit_form.html.erb
<%= simple_form_for [trip_location] do |f| %>
 <div class= "row g-3">
    <%= simple_fields_for(location) do |l| %>
      <div class = "col-md-12">
        <%= l.input :address %>
      </div>
    <% end %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/trip_locations/edit.html.erb
<div class= "container mt-5">
  <% if @trip_location.starting_location == true %>
    <h1>Editer le point de départ</h1>
  <% elsif @trip_location.target_location == true %>
    <h1>Editer le point d'arrivée</h1>
  <% end %>
    <%= link_to "Retour",trip_path(@trip_location.trip), class: "link-secondary"%>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render "edit_form", trip_location: @trip_location, location: @trip_location.location %>
    </div>
</div>

app/views/trip_locations/new.html.erb
<div class= "container mt-5">
  <% if params[:starting_location] %>
    <h1>Ajouter un point de départ</h1>
  <% elsif params[:target_location] %>
    <h1>Ajouter un point d'arrivée</h1>
  <% end %>
    <%= link_to "Retour",trip_path(@trip), class: "link-secondary"%>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render "create_form", trip: @trip, trip_location: @trip_location, location: @location %>
    </div>
</div>

app/views/trips/_banner.html.erb
<% if trip.cover_picture.attached? %>
  <div class="trip-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= trip.cover_picture.url %>)">
<% else %>
  <div class="trip-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/ds3lr3hfq/image/upload/v1666186058/default_cover_picture_xzxuhg.jpg')">
<% end %>
  <div class="container">
    <h1><strong><%= trip.title.capitalize %></strong></h1>
    <p><%= trip.short_description %></p>
    <div class="btn-placeholder d-flex justify-content-center">
      <%= link_to "Modifier", edit_trip_path(@trip), class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= simple_form_for(trip) do |f| %>
  <div class= "row g-3">
    <div class = "col-md-6">
      <%= f.input :title,
                  label:       "Titre",
                  placeholder: "Ex: Promenade à la mer" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :short_description,
                  label:       "Description courte",
                  placeholder: "Ex: Une magnifique promenade le long du Lez" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :difficulty,
                  label:       "Difficulté",
                  hint:        "Sur /10",
                  placeholder: "Ex: 8" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :length,
                  label:       "Durée en minutes",
                  placeholder: "Ex: 60" %>
    </div>
    <div class = "col-md-6">
      <%= f.input :cover_picture,
                  label:       "Image de couverture",
                  as:          :file %>
    </div>
  </div>
  <%= f.submit class:'btn btn-primary' %>
<% end %>

app/views/trips/_reviews.html.erb
<% if trip.reviews.count > 0 %>
    <% trip.reviews.each do |review| %>
        <div class="card w-50 mb-3">
            <div class="card-body">
                <h5 class="card-title"><%= review.rating %>/10</h5>
                <p class="card-text"><%= review.content %></p>
                <%=link_to "Modifier", edit_review_path(review), class: "btn btn-light"%>
                <%= link_to "Supprimer", review_path(trip),
                data: { turbo_method:  :delete,
                        turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet avis ?"
                                                     },
                class: "btn btn-danger"%>
            </div>
        </div>
    <% end %>
<% else %>
    <p> Oops ! Il n'y a pas encore d'avis pour cet itinéraire. </p>
<% end %>

app/views/trips/_trip-card.html.erb
<div class="card mb-3">
  <% if trip.cover_picture.attached? %>
    <img class="card-img-top" src="<%= trip.cover_picture.url %>" alt="Card image cap">
  <% else %>
    <img class="card-img-top" src="https://res.cloudinary.com/ds3lr3hfq/image/upload/v1666186058/default_cover_picture_xzxuhg.jpg" alt="Card image cap">
  <% end %>
  <div class="card-body">
    <div class="d-flex align-item mb-3">
      <span class="badge rounded-pill bg-dark">Difficulté : <%= trip.difficulty %>/10</span>
      <span class="badge rounded-pill bg-dark mx-2"><%= trip.length %> mn</span>
    </div>
    <h5 class="card-title"><%= trip.title %></h5>
    <p class="card-text"><%= trip.short_description %></p>
    <%= link_to 'Voir', trip_path(trip), class: 'btn btn-primary mt-3' %>
  </div>
</div>

app/views/trips/_trip.html.erb
<div>
  <div class= "trip-general-information mt-3">
    <div class="card mb-3">
      <div class="card-body">
        <p> <strong> Difficulté: </strong> <%= trip.difficulty%>/10</p>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <p> <strong> Durée: </strong> <%= trip.length%> mn</p>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <p> <strong> Départ: </strong> <%= trip.display_origin_address %></p>
        <% if trip.origin_address.nil? %>
          <%= link_to 'Ajouter', new_trip_trip_location_path(trip, starting_location: true), class: "btn btn-primary"  %>
        <% else %>
          <%= link_to 'Modifier', edit_trip_location_path(trip.trip_locations.find_by(starting_location: true)), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <p> <strong> Arrivée: </strong> <%= trip.display_target_address %></p>
        <% if trip.target_address.nil? %>
          <%= link_to 'Ajouter', new_trip_trip_location_path(trip, target_location: true), class: "btn btn-primary"  %>
        <% else %>
          <%= link_to 'Modifier', edit_trip_location_path(trip.trip_locations.find_by(target_location: true)), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/easy.html.erb
<div class= "container mt-5">
    <%= link_to "Retour", root_path, class:"link-secondary" %>
    <% @trips.each do |t| %>
        <%= render 'trip', trip: t %>
    <% end %>
</div> 

app/views/trips/edit.html.erb
<div class= "container mt-5">
    <%= link_to "Retour", trip_path(@trip), class: "link-secondary" %>
    <h1> Modifiez cet itinéraire </h1>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render 'form', trip: @trip  %>
    </div>
</div>

app/views/trips/hard.html.erb
<div class= "container mt-5">
    <%= link_to "Retour", root_path, class:"link-secondary" %>
    <% @trips.each do |t| %>
        <%= render 'trip', trip: t %>
    <% end %>
</div> 

app/views/trips/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.guide-du-paysbasque.com/_bibli/articlesPage/228/images/noa-adventure9.jpg?v=ficheArticle&width=416&height=275&pixelRatio=2.6250);">
  <div class="container">
    <h1>Bienvenue sur <strong>Lanes</strong></h1>
    <p>Partez à l'aventure en explorant nos <%=@trips.count%> itinéraires à vélo ou ajouter le votre.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>
<div class= "container mt-5">
  <div class="row">
    <% @trips.each do |trip| %>
      <div class = "col-sm-4">
        <%= render 'trip-card', trip: trip %>
      </div>
    <% end %>
  </div>
  <div>
      <%= link_to "Ajouter un itinéraire", new_trip_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/trips/new.html.erb
<div class= "container mt-5">
    <%= link_to "Retour", root_path, class: "link-secondary" %>
    <h1> Ajoutez un nouvel itinéraire </h1>
    <div class= "mt-4 bg-light p-5 rounded ">
      <%= render 'form', trip: @trip  %>
    </div>
</div>

app/views/trips/show.html.erb
<%= render 'banner', trip: @trip %>
<div class= "container mt-5">
  <%= link_to "Retour à tous les itinéraires", root_path, class:"link-secondary" %>
  <div class= "trip-presentation mt-5">
      <h2> Aperçu </h2>
      <div class = "row">
        <div class = "col-sm-4">
          <div>
            <%= render 'trip', trip: @trip %>
          </div>
          <%= link_to "Supprimer", trip_path(@trip),
            data: { turbo_method: :delete,
                    turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet itinéraire ?"
                    } ,
            class: "btn btn-danger"
          %>
        </div>
        <div class="col-sm-8">
          <% if @trip.is_missing_origin_or_target_address %>
            <p> Merci de bien vouloir remplir l'adresse de départ et d'arrivée pour afficher la carte </p>
          <% else %>
            <div data-controller = "map">
              <div style="width: 100%; height: 600px;"
                  data-controller="map"
                  data-map-markers-value="<%= @markers.to_json %>"
                  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </div>
  <div class = "mt-5">
      <h2> Avis </h2>
      <%= render 'reviews', trip: @trip %>
      <%= link_to "Ajouter un avis", new_trip_review_path(@trip), class: "btn btn-light mt-3"  %>
  </div>
</div>